/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JPanel;
import model.ServiceCatalog;
import model.VehicleDirectory;

/**
 * Shai Rashada-Parasram
 * INFO5100
 * Assignment: The Class Relationship Model
 * Date: 10/02/2026
 * File: HomeJPanel.java
 *
 * This panel represents the manager dashboard for the
 * Shai Vehicle Service Center application.
 *
 * @author shai8
 */
public class HomeJPanel extends javax.swing.JPanel {

    // References received from MainJFrame
    private JPanel mainWorkArea;
    private ServiceCatalog serviceCatalog;
    private VehicleDirectory vehicleDirectory;

    /**
     * Default constructor used by NetBeans.
     */
    public HomeJPanel() {
        initComponents();
    }

    /**
     * Constructor used by MainJFrame.
     */
    public HomeJPanel(JPanel mainWorkArea,
                      ServiceCatalog serviceCatalog,
                      VehicleDirectory vehicleDirectory) {

        initComponents();

        this.mainWorkArea = mainWorkArea;
        this.serviceCatalog = serviceCatalog;
        this.vehicleDirectory = vehicleDirectory;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnManageServices = new javax.swing.JButton();
        btnAddVehicle = new javax.swing.JButton();
        btnSearchVehicle = new javax.swing.JButton();
        btnListVehicles = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Shai Vehicle Service Center");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Manager Dashboard");

        btnManageServices.setText("Manage Services");
        btnManageServices.setToolTipText("");
        btnManageServices.setPreferredSize(new java.awt.Dimension(170, 50));
        btnManageServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageServicesActionPerformed(evt);
            }
        });

        btnAddVehicle.setText("Add Vehicle");
        btnAddVehicle.setToolTipText("");
        btnAddVehicle.setPreferredSize(new java.awt.Dimension(170, 50));
        btnAddVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVehicleActionPerformed(evt);
            }
        });

        btnSearchVehicle.setText("Search Vehicle");
        btnSearchVehicle.setPreferredSize(new java.awt.Dimension(170, 50));

        btnListVehicles.setText("List Vehicles");
        btnListVehicles.setPreferredSize(new java.awt.Dimension(170, 50));
        btnListVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListVehiclesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSearchVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnManageServices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel1)
                        .addGap(0, 243, Short.MAX_VALUE)))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageServices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(476, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageServicesActionPerformed
      ManageServicesJPanel manageServicesPanel =
            new ManageServicesJPanel(
                    mainWorkArea,
                    serviceCatalog
            );

    mainWorkArea.add(
            manageServicesPanel,
            "ManageServices"
    );

    java.awt.CardLayout layout =
            (java.awt.CardLayout) mainWorkArea.getLayout();

    layout.show(
            mainWorkArea,
            "ManageServices"
    );
    }//GEN-LAST:event_btnManageServicesActionPerformed

    private void btnAddVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVehicleActionPerformed
        // TODO add your handling code here:
      AddVehicleJPanel addVehiclePanel =
            new AddVehicleJPanel(
                    mainWorkArea,
                    serviceCatalog,
                    vehicleDirectory
            );

    mainWorkArea.add(
            addVehiclePanel,
            "AddVehicle"
    );

    java.awt.CardLayout layout =
            (java.awt.CardLayout) mainWorkArea.getLayout();

    layout.show(
            mainWorkArea,
            "AddVehicle"
    );

    }//GEN-LAST:event_btnAddVehicleActionPerformed

    private void btnListVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListVehiclesActionPerformed
        // TODO add your handling code here:
       ListVehiclesJPanel listVehiclesPanel =
            new ListVehiclesJPanel(
                    mainWorkArea,
                    vehicleDirectory
            );

    mainWorkArea.add(
            listVehiclesPanel,
            "ListVehicles"
    );

    java.awt.CardLayout layout =
            (java.awt.CardLayout) mainWorkArea.getLayout();

    layout.show(
            mainWorkArea,
            "ListVehicles"
    ); 
    }//GEN-LAST:event_btnListVehiclesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVehicle;
    private javax.swing.JButton btnListVehicles;
    private javax.swing.JButton btnManageServices;
    private javax.swing.JButton btnSearchVehicle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
