/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JPanel;
import model.Owner;
import model.Service;
import model.ServiceCatalog;
import model.Vehicle;
import model.VehicleDirectory;

/**
 * Shai Rashada-Parasram
 * INFO5100
 * Assignment: The Class Relationship Model
 * Date: 10/02/2026
 * File: AddVehicleJPanel.java
 *
 * This panel allows the manager to register an owner,
 * register a vehicle, and assign a service to the vehicle.
 *
 * @author shai8
 */
public class AddVehicleJPanel extends javax.swing.JPanel {

    // References shared with the rest of the application
    private JPanel mainWorkArea;
    private ServiceCatalog serviceCatalog;
    private VehicleDirectory vehicleDirectory;

    /**
     * Default constructor used by NetBeans.
     */
    public AddVehicleJPanel() {
        initComponents();
    }

    /**
     * Constructor used when opening Add Vehicle from HomeJPanel.
     */
    public AddVehicleJPanel(JPanel mainWorkArea,
                            ServiceCatalog serviceCatalog,
                            VehicleDirectory vehicleDirectory) {

        initComponents();

        this.mainWorkArea = mainWorkArea;
        this.serviceCatalog = serviceCatalog;
        this.vehicleDirectory = vehicleDirectory;

        populateServiceComboBox();
    }

    /**
     * Loads the available services into the ComboBox.
     */
    private void populateServiceComboBox() {

        cmbService.removeAllItems();

        for (Service service : serviceCatalog.getServiceList()) {

            cmbService.addItem(
                    service.getServiceType()
                    + " - $"
                    + service.getCost()
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtOwnerId = new javax.swing.JTextField();
        txtOwnerFirstName = new javax.swing.JTextField();
        txtOwnerLastName = new javax.swing.JTextField();
        txtVehicleId = new javax.swing.JTextField();
        txtMake = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtRegistrationNumber = new javax.swing.JTextField();
        txtServiceDate = new javax.swing.JTextField();
        btnAddVehicle = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        cmbService = new javax.swing.JComboBox<>();

        jLabel1.setText("Owner ID: ");

        jLabel2.setText("Owner First name: ");

        jLabel3.setText("Owner Last Name: ");

        jLabel4.setText("Vehicle ID:");

        jLabel5.setText("Make:");

        jLabel6.setText("Model:");

        jLabel7.setText("Year:");

        jLabel8.setText("Registration Number:");

        jLabel9.setText("Service Date:");

        jLabel10.setText("Service Opted:");

        txtOwnerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerIdActionPerformed(evt);
            }
        });

        btnAddVehicle.setText("Add Vehicle");
        btnAddVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVehicleActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cmbService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(107, 107, 107)))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtYear, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                            .addComponent(txtModel)
                            .addComponent(txtVehicleId, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtOwnerId)
                            .addComponent(txtOwnerLastName)
                            .addComponent(txtOwnerFirstName)
                            .addComponent(txtMake, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(200, 200, 200))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbService, 0, 551, Short.MAX_VALUE)
                            .addComponent(txtServiceDate)
                            .addComponent(txtRegistrationNumber))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtOwnerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOwnerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtOwnerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtVehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtRegistrationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtServiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddVehicle)
                    .addComponent(btnClear)
                    .addComponent(btnBack))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtOwnerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerIdActionPerformed

    private void cmbServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbServiceActionPerformed

    private void btnAddVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVehicleActionPerformed
        // TODO add your handling code here:
          if (txtOwnerId.getText().trim().isEmpty()
            || txtOwnerFirstName.getText().trim().isEmpty()
            || txtOwnerLastName.getText().trim().isEmpty()
            || txtVehicleId.getText().trim().isEmpty()
            || txtMake.getText().trim().isEmpty()
            || txtModel.getText().trim().isEmpty()
            || txtYear.getText().trim().isEmpty()
            || txtRegistrationNumber.getText().trim().isEmpty()
            || txtServiceDate.getText().trim().isEmpty()
            || cmbService.getSelectedIndex() < 0) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "All owner and vehicle fields are required.",
                "Missing Information",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    try {

        // Read owner information
        long ownerId =
                Long.parseLong(txtOwnerId.getText().trim());

        String firstName =
                txtOwnerFirstName.getText().trim();

        String lastName =
                txtOwnerLastName.getText().trim();

        // Read vehicle information
        int vehicleId =
                Integer.parseInt(txtVehicleId.getText().trim());

        String make =
                txtMake.getText().trim();

        String model =
                txtModel.getText().trim();

        int year =
                Integer.parseInt(txtYear.getText().trim());

        String registrationNumber =
                txtRegistrationNumber.getText().trim();

        String serviceDate =
                txtServiceDate.getText().trim();

        // Validate Owner ID
        if (ownerId <= 0) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Owner ID must be greater than 0.",
                    "Invalid Owner ID",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        // Validate Vehicle ID
        if (vehicleId <= 0) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Vehicle ID must be greater than 0.",
                    "Invalid Vehicle ID",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        // Validate year
        if (year < 1900 || year > 2100) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please enter a valid vehicle year.",
                    "Invalid Year",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        // Check for duplicate Vehicle ID
        for (Vehicle vehicle : vehicleDirectory.getVehicleList()) {

            if (vehicle.getVehicleId() == vehicleId) {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "A vehicle with this Vehicle ID already exists.",
                        "Duplicate Vehicle ID",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                );

                return;
            }
        }

        // Get selected service
        int selectedServiceIndex =
                cmbService.getSelectedIndex();

        Service selectedService =
                serviceCatalog.getServiceList().get(selectedServiceIndex);

        // Create owner
        Owner newOwner = new Owner(
                ownerId,
                firstName,
                lastName
        );

        // Create vehicle
        Vehicle newVehicle = new Vehicle(
                vehicleId,
                make,
                model,
                year,
                registrationNumber,
                serviceDate,
                newOwner,
                selectedService
        );

        // Add vehicle to directory
        vehicleDirectory.addVehicle(newVehicle);

        // Success message
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Vehicle registered successfully."
        );

        // Clear fields after successful registration
        txtOwnerId.setText("");
        txtOwnerFirstName.setText("");
        txtOwnerLastName.setText("");

        txtVehicleId.setText("");
        txtMake.setText("");
        txtModel.setText("");
        txtYear.setText("");
        txtRegistrationNumber.setText("");
        txtServiceDate.setText("");

        if (cmbService.getItemCount() > 0) {
            cmbService.setSelectedIndex(0);
        }

    } catch (NumberFormatException e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Owner ID, Vehicle ID, and Year must contain valid numbers.",
                "Invalid Input",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    
    }//GEN-LAST:event_btnAddVehicleActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
         txtOwnerId.setText("");
    txtOwnerFirstName.setText("");
    txtOwnerLastName.setText("");

    txtVehicleId.setText("");
    txtMake.setText("");
    txtModel.setText("");
    txtYear.setText("");
    txtRegistrationNumber.setText("");
    txtServiceDate.setText("");

    if (cmbService.getItemCount() > 0) {
        cmbService.setSelectedIndex(0);
    }
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         java.awt.CardLayout layout =
            (java.awt.CardLayout) mainWorkArea.getLayout();

    layout.show(mainWorkArea, "Home");
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVehicle;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JComboBox<String> cmbService;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtOwnerFirstName;
    private javax.swing.JTextField txtOwnerId;
    private javax.swing.JTextField txtOwnerLastName;
    private javax.swing.JTextField txtRegistrationNumber;
    private javax.swing.JTextField txtServiceDate;
    private javax.swing.JTextField txtVehicleId;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
