/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Vehicle;
import model.VehicleDirectory;

/**
 *
 * @author shai8
 */
public class ListVehiclesJPanel extends javax.swing.JPanel {

    // Reference to the main CardLayout panel
    private JPanel mainWorkArea;

    // Shared vehicle directory
    private VehicleDirectory vehicleDirectory;

    /**
     * Default constructor used by NetBeans GUI Builder.
     */
    public ListVehiclesJPanel() {
        initComponents();
    }

    /**
     * Constructor used when opening List Vehicles from HomeJPanel.
     *
     * @param mainWorkArea the main CardLayout panel
     * @param vehicleDirectory the application's vehicle directory
     */
    public ListVehiclesJPanel(JPanel mainWorkArea,
                              VehicleDirectory vehicleDirectory) {

        initComponents();
        
      this.mainWorkArea = mainWorkArea;
    this.vehicleDirectory = vehicleDirectory;

    // Load vehicles into the table
    populateTable();

    // Connect the Back button directly
    btnBack.addActionListener(e -> {

        java.awt.CardLayout layout =
                (java.awt.CardLayout) this.mainWorkArea.getLayout();

        layout.show(this.mainWorkArea, "Home");
    });
}  
    
    /**
 * Loads all vehicles from VehicleDirectory into the table.
 */
private void populateTable() {

    DefaultTableModel model =
            (DefaultTableModel) tblVehicles.getModel();

    model.setRowCount(0);

    for (Vehicle vehicle : vehicleDirectory.getVehicleList()) {

        Object[] row = new Object[8];

        row[0] = vehicle.getVehicleId();
        row[1] = vehicle.getMake();
        row[2] = vehicle.getModel();
        row[3] = vehicle.getYear();
        row[4] = vehicle.getRegistrationNumber();
        row[5] = vehicle.getServiceDate();

        if (vehicle.getOwner() != null) {
            row[6] = vehicle.getOwner().getFullName();
        } else {
            row[6] = "";
        }

        if (vehicle.getService() != null) {
            row[7] = vehicle.getService().getServiceType();
        } else {
            row[7] = "";
        }

        model.addRow(row);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        table = new javax.swing.JScrollPane();
        tblVehicles = new javax.swing.JTable();
        btnViewVehicle = new javax.swing.JButton();
        btnDeleteVehicle = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("        Vehicle Directory");

        tblVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Vehicle ID", "Make", "Model", "Year", "Registration Number", "Service Date", "Owner Name", "Service Select"
            }
        ));
        table.setViewportView(tblVehicles);

        btnViewVehicle.setText("View Vehicle ");
        btnViewVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewVehicleActionPerformed(evt);
            }
        });

        btnDeleteVehicle.setText("Delete Vehicle");
        btnDeleteVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVehicleActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnViewVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(btnDeleteVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteVehicle)
                    .addComponent(btnBack)
                    .addComponent(btnViewVehicle))
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVehicleActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblVehicles.getSelectedRow();

if (selectedRow < 0) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please select a vehicle from the table first.",
            "No Vehicle Selected",
            javax.swing.JOptionPane.ERROR_MESSAGE
    );

    return;
}

// Get the Vehicle ID from the selected table row
int vehicleId =
        Integer.parseInt(
                tblVehicles.getValueAt(selectedRow, 0).toString()
        );

// Find the matching Vehicle object
Vehicle selectedVehicle = null;

for (Vehicle vehicle : vehicleDirectory.getVehicleList()) {

    if (vehicle.getVehicleId() == vehicleId) {
        selectedVehicle = vehicle;
        break;
    }
}

// Make sure the vehicle was found
if (selectedVehicle == null) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Vehicle could not be found.",
            "Vehicle Not Found",
            javax.swing.JOptionPane.ERROR_MESSAGE
    );

    return;
}

// Ask the user to confirm deletion
int choice =
        javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete this vehicle?",
                "Confirm Delete",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

// Delete only if the user chooses Yes
if (choice == javax.swing.JOptionPane.YES_OPTION) {

    vehicleDirectory.deleteVehicle(selectedVehicle);

    // Refresh the table
    populateTable();

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Vehicle deleted successfully."
    );
}




    }//GEN-LAST:event_btnDeleteVehicleActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here
         java.awt.CardLayout layout =
            (java.awt.CardLayout) mainWorkArea.getLayout();

    layout.show(mainWorkArea, "Home");

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewVehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewVehicleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteVehicle;
    private javax.swing.JButton btnViewVehicle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane table;
    private javax.swing.JTable tblVehicles;
    // End of variables declaration//GEN-END:variables
}
