/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Service;
import model.ServiceCatalog;

/**
 * Shai Rashada-Parasram
 * INFO5100
 * Assignment: The Class Relationship Model
 * Date: 10/02/2026
 * File: ManageServicesJPanel.java
 *
 * This panel allows the manager to view and manage
 * services offered by the vehicle service center.
 *
 * @author shai8
 */
public class ManageServicesJPanel extends javax.swing.JPanel {

    private JPanel mainWorkArea;
    private ServiceCatalog serviceCatalog;

    public ManageServicesJPanel() {
        initComponents();
    }

    public ManageServicesJPanel(JPanel mainWorkArea,
                                ServiceCatalog serviceCatalog) {

        initComponents();

        this.mainWorkArea = mainWorkArea;
        this.serviceCatalog = serviceCatalog;

        populateTable();
    }

    private void populateTable() {

    DefaultTableModel model =
            (DefaultTableModel) tblServices.getModel();

    model.setRowCount(0);

    for (Service service : serviceCatalog.getServiceList()) {

        Object[] row = new Object[5];

        row[0] = service.getServiceId();
        row[1] = service.getServiceType();
        row[2] = service.getCost();
        row[3] = service.getMechanicName();
        row[4] = service.getServiceDuration();

        model.addRow(row);
    }
}

private void loadSelectedService() {

    int selectedRow = tblServices.getSelectedRow();

    if (selectedRow < 0) {
        return;
    }

    txtServiceId.setText(
            tblServices.getValueAt(selectedRow, 0).toString()
    );

    txtServiceType.setText(
            tblServices.getValueAt(selectedRow, 1).toString()
    );

    txtCost.setText(
            tblServices.getValueAt(selectedRow, 2).toString()
    );

    txtMechanicName.setText(
            tblServices.getValueAt(selectedRow, 3).toString()
    );

    txtServiceDuration.setText(
            tblServices.getValueAt(selectedRow, 4).toString()
    );
}
 



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblServiceId = new javax.swing.JLabel();
        lblServiceType = new javax.swing.JLabel();
        lblCost = new javax.swing.JLabel();
        lblMechanicName = new javax.swing.JLabel();
        lblServiceDuration = new javax.swing.JLabel();
        btnAddService = new javax.swing.JButton();
        btnUpdateService = new javax.swing.JButton();
        btnDeleteServic = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtServiceId = new javax.swing.JTextField();
        txtServiceType = new javax.swing.JTextField();
        txtCost = new javax.swing.JTextField();
        txtMechanicName = new javax.swing.JTextField();
        txtServiceDuration = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServices = new javax.swing.JTable();

        lblServiceId.setText("Service ID:");

        lblServiceType.setText("Service Type:");

        lblCost.setText("Cost:");

        lblMechanicName.setText("Mechanic Name:");

        lblServiceDuration.setText("Service Duration:");

        btnAddService.setText("Add Service");
        btnAddService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServiceActionPerformed(evt);
            }
        });

        btnUpdateService.setText("Update Service");
        btnUpdateService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateServiceActionPerformed(evt);
            }
        });

        btnDeleteServic.setText("Delete Service");
        btnDeleteServic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteServicActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtServiceId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceIdActionPerformed(evt);
            }
        });

        txtServiceType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceTypeActionPerformed(evt);
            }
        });

        tblServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Service Type", "Cost", "Mechanic", "Duration"
            }
        ));
        tblServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServicesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblServices);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMechanicName)
                    .addComponent(lblServiceType)
                    .addComponent(lblServiceId)
                    .addComponent(lblCost)
                    .addComponent(lblServiceDuration))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtServiceDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtServiceType)
                        .addComponent(txtCost)
                        .addComponent(txtServiceId)
                        .addComponent(txtMechanicName, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddService, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btnUpdateService, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(btnDeleteServic, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServiceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServiceId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServiceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServiceType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMechanicName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMechanicName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServiceDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServiceDuration))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateService)
                    .addComponent(btnAddService)
                    .addComponent(btnDeleteServic)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblServiceId.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void txtServiceIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceIdActionPerformed

    private void txtServiceTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceTypeActionPerformed

    private void btnAddServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServiceActionPerformed
         if (txtServiceId.getText().trim().isEmpty()
            || txtServiceType.getText().trim().isEmpty()
            || txtCost.getText().trim().isEmpty()
            || txtMechanicName.getText().trim().isEmpty()
            || txtServiceDuration.getText().trim().isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "All service fields are required.",
                "Missing Information",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    try {

        int serviceId =
                Integer.parseInt(txtServiceId.getText().trim());

        String serviceType =
                txtServiceType.getText().trim();

        double cost =
                Double.parseDouble(txtCost.getText().trim());

        String mechanicName =
                txtMechanicName.getText().trim();

        short serviceDuration =
                Short.parseShort(txtServiceDuration.getText().trim());

        if (serviceCatalog.searchServiceById(serviceId) != null) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "A service with this Service ID already exists.",
                    "Duplicate Service ID",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        if (serviceId <= 0) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Service ID must be greater than 0.",
                    "Invalid Service ID",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        if (cost < 0) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Cost cannot be negative.",
                    "Invalid Cost",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        if (serviceDuration <= 0) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Service duration must be greater than 0.",
                    "Invalid Duration",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        Service newService = new Service(
                serviceId,
                serviceType,
                cost,
                mechanicName,
                serviceDuration
        );

        serviceCatalog.addService(newService);

        populateTable();

        txtServiceId.setText("");
        txtServiceType.setText("");
        txtCost.setText("");
        txtMechanicName.setText("");
        txtServiceDuration.setText("");

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Service added successfully."
        );

    } catch (NumberFormatException e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Service ID, Cost, and Service Duration must contain valid numbers.",
                "Invalid Input",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
      }
       
    }//GEN-LAST:event_btnAddServiceActionPerformed

    private void btnUpdateServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateServiceActionPerformed
         int selectedRow = tblServices.getSelectedRow();
            if (selectedRow < 0) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please select a service from the table first.",
                "No Service Selected",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    if (txtServiceId.getText().trim().isEmpty()
            || txtServiceType.getText().trim().isEmpty()
            || txtCost.getText().trim().isEmpty()
            || txtMechanicName.getText().trim().isEmpty()
            || txtServiceDuration.getText().trim().isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "All service fields are required.",
                "Missing Information",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    try {

        int serviceId =
                Integer.parseInt(txtServiceId.getText().trim());

        String serviceType =
                txtServiceType.getText().trim();

        double cost =
                Double.parseDouble(txtCost.getText().trim());

        String mechanicName =
                txtMechanicName.getText().trim();

        short serviceDuration =
                Short.parseShort(
                        txtServiceDuration.getText().trim()
                );

        Service selectedService =
                serviceCatalog.searchServiceById(serviceId);

        if (selectedService == null) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Service could not be found.",
                    "Service Not Found",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        if (serviceId <= 0) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Service ID must be greater than 0.",
                    "Invalid Service ID",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        if (cost < 0) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Cost cannot be negative.",
                    "Invalid Cost",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        if (serviceDuration <= 0) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Service duration must be greater than 0.",
                    "Invalid Duration",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        selectedService.setServiceType(serviceType);
        selectedService.setCost(cost);
        selectedService.setMechanicName(mechanicName);
        selectedService.setServiceDuration(serviceDuration);

        populateTable();

        txtServiceId.setText("");
        txtServiceType.setText("");
        txtCost.setText("");
        txtMechanicName.setText("");
        txtServiceDuration.setText("");

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Service updated successfully."
        );

    } catch (NumberFormatException e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Service ID, Cost, and Service Duration must contain valid numbers.",
                "Invalid Input",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnUpdateServiceActionPerformed

    private void tblServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServicesMouseClicked
        loadSelectedService();
    }//GEN-LAST:event_tblServicesMouseClicked

    private void btnDeleteServicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteServicActionPerformed
        
         int selectedRow = tblServices.getSelectedRow();

        if (selectedRow < 0) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please select a service from the table first.",
            "No Service Selected",
            javax.swing.JOptionPane.ERROR_MESSAGE
    );

    return;
}

int serviceId =
        Integer.parseInt(
                tblServices.getValueAt(selectedRow, 0).toString()
        );

Service selectedService =
        serviceCatalog.searchServiceById(serviceId);

if (selectedService == null) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Service could not be found.",
            "Service Not Found",
            javax.swing.JOptionPane.ERROR_MESSAGE
    );

    return;
}

int choice =
        javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete this service?",
                "Confirm Delete",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

if (choice == javax.swing.JOptionPane.YES_OPTION) {

    serviceCatalog.deleteService(selectedService);

    populateTable();

    txtServiceId.setText("");
    txtServiceType.setText("");
    txtCost.setText("");
    txtMechanicName.setText("");
    txtServiceDuration.setText("");

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Service deleted successfully."
    );
}
    }//GEN-LAST:event_btnDeleteServicActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
          java.awt.CardLayout layout =
            (java.awt.CardLayout) mainWorkArea.getLayout();

    layout.show(mainWorkArea, "Home");
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddService;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteServic;
    private javax.swing.JButton btnUpdateService;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblMechanicName;
    private javax.swing.JLabel lblServiceDuration;
    private javax.swing.JLabel lblServiceId;
    private javax.swing.JLabel lblServiceType;
    private javax.swing.JTable tblServices;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtMechanicName;
    private javax.swing.JTextField txtServiceDuration;
    private javax.swing.JTextField txtServiceId;
    private javax.swing.JTextField txtServiceType;
    // End of variables declaration//GEN-END:variables
}
